### ISSUE TITLE
Getting an error: "Bad Plugin file"

### ISSUE THREAD

**Issue by Banellica** [cybereality/eog-modified-date-plugin#3]
Following the instructions, after copying the folder and starting eog, I am getting this error:

(eog:32288): libpeas-WARNING **: 21:42:12.000: Bad plugin file '/home/johnny/.local/share/eog/plugins/modified-date/modified-date.plugin': Key file contains line \“\<!DOCTYPE html\>\” which is not a key-value pair, group, or comment

(eog:32288): libpeas-WARNING **: 21:42:12.000: Error loading '/home/johnny/.local/share/eog/plugins/modified-date/modified-date.plugin'

System: Ubuntu 18.04.5, eog 3.28.1

**Comment by cybereality** [comment]
Thanks for reporting this. I just tested on Ubuntu 18.04.6, and it seems to be mostly working. There was a small issue with the UI, which I just fixed, but I don't think that was related to your problem. Most likely what happened is that when you downloaded the file from GitHub, it actually downloaded the HTML version of the file and not the raw original file (sorry if this is confusing). I would recommend downloading the zip file from this link, I just confirmed it is working. Then you'll just have to extract the zip and copy the modified-date folder (be sure to delete the corrupted one first). Thanks.
https://github.com/cybereality/eog-modified-date-plugin/archive/refs/heads/main.zip

**Comment by cybereality** [comment]
Thanks for pointing this out, though. I have updated the main page on GitHub to include a download link to make it a little easier. Cheers.

**Comment by Banellica** [comment]
It's working now.
Thank you for your good work.

**Comment by cybereality** [comment]
Awesome! Thanks so much for trying my plugin.
